### ISSUE TITLE
Attachments are stored in working directory

### ISSUE THREAD

**Issue by missytake** [deltachat-bot/deltawoot#4]
We should store them in some subdirectory; or change the working directory to something else than `$HOME`.

**Comment by missytake** [comment]
Otherwise, this can be a problem if an agent sends a file that is called entrypoint.sh, and then the container is restarted.

**Comment by missytake** [comment]
Ah, at least it is no security problem, just an annoying bug because the file can't be send, but no error is shown:

```
2024-07-25T09:41:08.050672558Z Traceback (most recent call last):
2024-07-25T09:41:08.050701957Z   File "/home/deltawoot/.local/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
2024-07-25T09:41:08.050719992Z     return self.wsgi_app(environ, start_response)
2024-07-25T09:41:08.050725571Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T09:41:08.050729802Z   File "/home/deltawoot/.local/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
2024-07-25T09:41:08.050734484Z     response = self.handle_exception(e)
2024-07-25T09:41:08.050738734Z                ^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T09:41:08.050763989Z   File "/home/deltawoot/.local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
2024-07-25T09:41:08.050767651Z     response = self.full_dispatch_request()
2024-07-25T09:41:08.050770768Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T09:41:08.050773919Z   File "/home/deltawoot/.local/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
2024-07-25T09:41:08.050777257Z     rv = self.handle_user_exception(e)
2024-07-25T09:41:08.050780329Z          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T09:41:08.050783423Z   File "/home/deltawoot/.local/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
2024-07-25T09:41:08.050786705Z     rv = self.dispatch_request()
2024-07-25T09:41:08.050789840Z          ^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T09:41:08.050793083Z   File "/home/deltawoot/.local/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
2024-07-25T09:41:08.050796899Z     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
2024-07-25T09:41:08.050801706Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T09:41:08.050806192Z   File "/home/deltawoot/.local/lib/python3.11/site-packages/deltawoot/send.py", line 22, in pass_woot_to_delta
2024-07-25T09:41:08.050811107Z     filename = download_file(url)
2024-07-25T09:41:08.050815674Z                ^^^^^^^^^^^^^^^^^^
2024-07-25T09:41:08.050820232Z   File "/home/deltawoot/.local/lib/python3.11/site-packages/deltawoot/send.py", line 38, in download_file
2024-07-25T09:41:08.050824963Z     with open(file_name, 'wb') as f:
2024-07-25T09:41:08.050830305Z          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-25T09:41:08.050833648Z PermissionError: [Errno 13] Permission denied: 'entrypoint.sh'
```
